# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
      
    - name: set environment variables
      run: |
          echo "CC_TEST_REPORTER_ID=${{secrets.CC_TEST_REPORTER_ID}}" >> $GITHUB_ENV
          echo "JACOCO_SOURCE_PATH=src/main/java" >> $GITHUB_ENV
          echo "GIT_COMMIT_SHA=${{github.sha}}" >> $GITHUB_ENV
          echo "GIT_BRANCH_REF=${{github.ref}}" >> $GITHUB_ENV
          
    - name: cc test coverage prebuilt
      run: |
        curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
        chmod +x ./cc-test-reporter
        ./cc-test-reporter before-build

    - name: Build with Maven
      run: mvn -B deploy -s .github/workflows/settings.xml -Drepo.username=mourezwell -Drepo.token=${{ secrets.GITHUB_TOKEN }} -Dsonar.login=${{secrets.SONAR_LOGIN}}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: cc test coverage postbuilt
      run: |
        export GIT_BRANCH=${GIT_BRANCH_REF:11}
        ./cc-test-reporter format-coverage -t jacoco ./target/site/jacoco/jacoco.xml
        ./cc-test-reporter upload-coverage --debug

